#!/usr/bin/env python3
"""
pm_dashboard_smoke.py — actually run the generated dashboard, headlessly
(S027.T001_BuildAgileDashboard).

## Why this exists

The dashboard is ~400 KB of hand-written JavaScript rendering twenty SVG charts
from a derived payload. Reading it cannot tell you whether it runs, and three
of its most likely failure modes are *silent*:

1. **A hallucinated API call.** `PM.svg.chart()` has a specific option shape;
   a module that passes `{yDomain: ...}` instead of `{y: {domain: ...}}`
   throws, or worse, quietly scales everything to [0,1].
2. **`NaN` in an SVG attribute.** `d="M NaN,12 L ..."` does not error. The
   browser draws nothing, the card looks deliberately empty, and the number the
   reader wanted is simply absent with no indication anything went wrong. This
   is the single most dangerous bug class in a dashboard, because a blank chart
   reads as "no data" rather than "broken".
3. **A crash on an empty series.** Every array in the payload can be empty on
   some other project, and a view that indexes `[0]` unguarded takes its whole
   tab down there while working perfectly here.

None of that is visible without executing the code. So this module builds a
minimal DOM, loads the real concatenated sources against the real payload,
invokes every registered view, and reports what happened — including a sweep of
every attribute every chart set, looking for `NaN`, `undefined`, `null` and
`Infinity`.

## Why the driver is generated rather than checked in

[[.ai/workflow/decisions/0003-python-only-scripting|ADR-0003]] makes Python the
only scripting language for checked-in automation, and is explicit about the
remedy when a platform tool is needed: "a Python script that shells out via
`subprocess` to the OS-native command, not a native shell script". A checked-in
`.js` harness would be a second scripting language for automation; this module
is Python, and the JavaScript it writes to a temporary file is a generated
artifact, the same way `subprocess` arguments are.

Node is optional. Absent, this reports `available: False` and exits 0 — it is a
diagnostic, and a missing interpreter is not a dashboard defect. Callers that
want a gate read the `ok` field, never the exit code alone.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

SCRIPTS_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPTS_DIR.parents[1]
ASSET_DIR = REPO_ROOT / ".ai" / "dashboard"

if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

TABS = (
    "overview", "burn", "flow", "forecast", "board", "roadmap",
    "backlog", "deps", "decisions", "activity", "debt", "data",
)

# Attribute values that mean a chart silently drew nothing.
POISON_RE = re.compile(r"\b(NaN|undefined|Infinity|-Infinity)\b")

DOM_SHIM = r"""
/* Generated by pm_dashboard_smoke.py. Not a checked-in script; see that
   module's docstring for why (ADR-0003). */
'use strict';

const SVG_NS = 'http://www.w3.org/2000/svg';
const issues = [];
const created = { total: 0, svg: 0 };

function flatten(node, out) {
  out = out || [];
  out.push(node);
  (node.childNodes || []).forEach(function (c) { flatten(c, out); });
  return out;
}

class ClassList {
  constructor(node) { this.node = node; this.set = new Set(); }
  add() { for (const c of arguments) if (c) String(c).split(/\s+/).forEach(x => x && this.set.add(x)); this.sync(); }
  remove() { for (const c of arguments) this.set.delete(c); this.sync(); }
  toggle(c, on) { if (on === undefined) { this.set.has(c) ? this.set.delete(c) : this.set.add(c); } else if (on) { this.set.add(c); } else { this.set.delete(c); } this.sync(); }
  contains(c) { return this.set.has(c); }
  sync() { this.node.attributes['class'] = Array.from(this.set).join(' '); }
}

class Style {
  constructor() { this.props = {}; }
  setProperty(name, value) { this.props[name] = value; }
  removeProperty(name) { delete this.props[name]; }
  getPropertyValue(name) { return this.props[name] || ''; }
}

class Node2 {
  constructor(tag, ns) {
    this.tagName = tag;
    this.namespaceURI = ns || null;
    this.childNodes = [];
    this.attributes = {};
    this.parentNode = null;
    this._text = '';
    this.style = new Style();
    this.dataset = {};
    this.listeners = {};
    this.hidden = false;
    this.tabIndex = 0;
    this.classList = new ClassList(this);
    this.clientWidth = tag === 'svg' ? 0 : 900;
    this.clientHeight = 300;
    this.value = '';
    this.disabled = false;
    created.total += 1;
    if (ns === SVG_NS) created.svg += 1;
  }

  get className() { return this.attributes['class'] || ''; }
  set className(v) { this.attributes['class'] = v; this.classList.set = new Set(String(v).split(/\s+/).filter(Boolean)); }

  appendChild(child) {
    if (child && child.__fragment) {
      child.childNodes.slice().forEach(c => this.appendChild(c));
      return child;
    }
    if (child) { child.parentNode = this; this.childNodes.push(child); }
    return child;
  }
  insertBefore(child, ref) {
    const i = this.childNodes.indexOf(ref);
    if (child) { child.parentNode = this; this.childNodes.splice(i < 0 ? this.childNodes.length : i, 0, child); }
    return child;
  }
  removeChild(child) {
    const i = this.childNodes.indexOf(child);
    if (i >= 0) this.childNodes.splice(i, 1);
    if (child) child.parentNode = null;
    return child;
  }
  remove() { if (this.parentNode) this.parentNode.removeChild(this); }
  replaceChildren() { this.childNodes = []; }

  get firstChild() { return this.childNodes[0] || null; }
  get lastChild() { return this.childNodes[this.childNodes.length - 1] || null; }
  get children() { return this.childNodes; }

  setAttribute(name, value) {
    this.attributes[name] = String(value);
    /* U.el() sets classes through setAttribute, not the className setter, so
       without this sync every classList query in the harness returns false and
       the card/KPI counts read as zero on a page full of cards. */
    if (name === 'class') {
      this.classList.set = new Set(String(value).split(/\s+/).filter(Boolean));
    }
    if (POISON_KEYS.has(name) || true) {
      if (/\b(NaN|undefined|Infinity)\b/.test(String(value))) {
        issues.push({ kind: 'poison-attribute', tag: this.tagName, attr: name, value: String(value).slice(0, 160) });
      }
    }
  }
  getAttribute(name) { return this.attributes[name] === undefined ? null : this.attributes[name]; }
  removeAttribute(name) { delete this.attributes[name]; }
  hasAttribute(name) { return this.attributes[name] !== undefined; }

  get textContent() {
    if (this.childNodes.length === 0) return this._text;
    return this.childNodes.map(c => c.textContent).join('');
  }
  set textContent(v) { this._text = v === null || v === undefined ? '' : String(v); this.childNodes = []; }

  addEventListener(type, fn) { (this.listeners[type] = this.listeners[type] || []).push(fn); }
  removeEventListener(type, fn) {
    const list = this.listeners[type] || [];
    const i = list.indexOf(fn); if (i >= 0) list.splice(i, 1);
  }
  dispatchEvent(ev) { (this.listeners[ev.type] || []).forEach(fn => fn(ev)); return true; }

  getBoundingClientRect() { return { left: 0, top: 0, width: this.clientWidth || 900, height: this.clientHeight || 300, right: 900, bottom: 300 }; }
  focus() {}
  blur() {}
  click() { this.dispatchEvent({ type: 'click', target: this }); }
  scrollIntoView() {}

  closest(sel) {
    let cur = this;
    const want = sel.replace(/^\./, '');
    while (cur) {
      if (cur.classList && cur.classList.contains(want)) return cur;
      if (cur.tagName === sel) return cur;
      cur = cur.parentNode;
    }
    return null;
  }
  matches(sel) { return this.classList.contains(sel.replace(/^\./, '')); }
  querySelector(sel) { return this.querySelectorAll(sel)[0] || null; }
  querySelectorAll(sel) {
    const want = sel.replace(/^\./, '').replace(/^#/, '');
    return flatten(this).filter(n => n !== this && (
      (n.classList && n.classList.contains(want)) ||
      n.tagName === sel || n.attributes.id === want
    ));
  }
}

const POISON_KEYS = new Set();

/* Extends Node2 rather than standing alone: 00-util's append() branches on
   `children instanceof Node`, so a text node outside that hierarchy would be
   stringified a second time instead of appended. */
class Text2 extends Node2 {
  constructor(text) { super('#text', null); this._text = String(text); }
}

class Fragment extends Node2 {
  constructor() { super('#fragment'); this.__fragment = true; }
}

const byId = {};

const document = {
  readyState: 'complete',
  createElement(tag) { return new Node2(tag, null); },
  createElementNS(ns, tag) { return new Node2(tag, ns); },
  createTextNode(t) { return new Text2(t); },
  createDocumentFragment() { return new Fragment(); },
  getElementById(id) { return byId[id] || null; },
  querySelector(sel) { return document.body.querySelector(sel); },
  querySelectorAll(sel) { return document.body.querySelectorAll(sel); },
  addEventListener() {},
  removeEventListener() {},
};

document.documentElement = new Node2('html', null);
document.documentElement.dataset = {};
document.body = new Node2('body', null);
document.body.dataset = {};
document.documentElement.appendChild(document.body);

/* The ids template.html guarantees (SCHEMA.md section 4). */
['pm-header', 'pm-tabs', 'pm-main', 'pm-tooltip', 'pm-project-name',
 'pm-project-sub', 'pm-generated-at', 'pm-footer-corpus', 'pm-theme-toggle',
 'pm-theme-label', 'pm-print', 'pm-filter-sprint', 'pm-filter-lane',
 'pm-data'].forEach(function (id) {
  const node = new Node2(id === 'pm-tabs' ? 'nav' : 'div', null);
  node.attributes.id = id;
  byId[id] = node;
  document.body.appendChild(node);
});
TAB_IDS.forEach(function (tab) {
  const panel = new Node2('section', null);
  panel.attributes.id = 'tab-' + tab;
  panel.classList.add('pm-panel');
  byId['tab-' + tab] = panel;
  byId['pm-main'].appendChild(panel);

  const button = new Node2('button', null);
  button.attributes.id = 'pm-tabbtn-' + tab;
  button.classList.add('pm-tab');
  button.dataset.tab = tab;
  byId['pm-tabbtn-' + tab] = button;
  byId['pm-tabs'].appendChild(button);
});

byId['pm-data'].textContent = PAYLOAD_TEXT;

/* Token values parsed out of the real 00-tokens.css light block, so the theme
   editor's is-this-a-colour detection runs against real input rather than a
   stub that would make every token look like a colour. */
const TOKENS = TOKEN_VALUES;

function defineGlobal(name, value) {
  try {
    Object.defineProperty(globalThis, name, {
      value: value, configurable: true, writable: true, enumerable: false,
    });
    return true;
  } catch (err) {
    return false;   /* a getter-only built-in, e.g. navigator on Node 18+ */
  }
}

/* In a browser `window` IS the global object, and every source depends on
   that: each opens with `window.PM = window.PM || {}` and then reads the bare
   identifier `PM`. With `window` as a separate plain object that assignment
   creates no global binding, and all twelve modules die on "PM is not
   defined" - which is exactly what the first run of this harness reported. So
   the shim installs its properties onto globalThis and aliases window to it. */
const winListeners = {};
const stubs = {
  document: document,
  Node: Node2,
  innerWidth: 1440,
  innerHeight: 900,
  devicePixelRatio: 1,
  location: { hash: '', href: 'file:///index.html', pathname: '/index.html' },
  history: { replaceState() {}, pushState() {} },
  localStorage: (function () {
    const store = {};
    return {
      getItem(k) { return k in store ? store[k] : null; },
      setItem(k, v) { store[k] = String(v); },
      removeItem(k) { delete store[k]; },
      clear() { for (const k in store) delete store[k]; },
    };
  })(),
  matchMedia(q) {
    return {
      matches: false, media: q,
      addEventListener() {}, removeEventListener() {},
      addListener() {}, removeListener() {},
    };
  },
  getComputedStyle(node) {
    return {
      getPropertyValue(name) {
        if (node && node.style && node.style.props[name]) return node.style.props[name];
        return TOKENS[name] || '';
      },
    };
  },
  addEventListener(type, fn) { (winListeners[type] = winListeners[type] || []).push(fn); },
  removeEventListener(type, fn) {
    const list = winListeners[type] || [];
    const i = list.indexOf(fn); if (i >= 0) list.splice(i, 1);
  },
  dispatchEvent(ev) { (winListeners[ev && ev.type] || []).forEach(fn => fn(ev)); return true; },
  print() {},
  requestAnimationFrame() { return 0; },
  /* Never fires: a debounce or an afterprint fallback that actually ran would
     re-enter rendering mid-measurement. */
  setTimeout() { return 0; },
  clearTimeout() {},
};
Object.keys(stubs).forEach(function (key) { defineGlobal(key, stubs[key]); });
defineGlobal('window', globalThis);

const ShimCustomEvent = globalThis.CustomEvent || class ShimCustomEvent {
  constructor(type, init) { this.type = type; this.detail = (init || {}).detail; }
};
const ShimBlob = globalThis.Blob || class ShimBlob {
  constructor(parts) { this.parts = parts; }
};
if (!globalThis.navigator || !globalThis.navigator.clipboard) {
  defineGlobal('navigator', { clipboard: { writeText() { return Promise.resolve(); } } });
}
const window = globalThis;

/* ---- load the real sources -------------------------------------------- */

SOURCES.forEach(function (src) {
  try {
    (new Function('window', 'document', 'localStorage', 'getComputedStyle',
                  'matchMedia', 'navigator', 'URL', 'Blob', 'CustomEvent',
                  'Node', 'setTimeout', 'clearTimeout', src.code))(
      window, document, window.localStorage, window.getComputedStyle,
      window.matchMedia.bind(window), window.navigator, window.URL, ShimBlob,
      ShimCustomEvent, Node2, window.setTimeout, window.clearTimeout);
  } catch (err) {
    issues.push({ kind: 'load-error', file: src.name, message: String(err && err.message || err), stack: String(err && err.stack || '').split('\n').slice(0, 4).join(' | ') });
  }
});

const PM = window.PM;
const result = { modules: {}, views: {}, issues: issues, created: created };

if (!PM) {
  result.fatal = 'window.PM was never defined; no source loaded successfully.';
  console.log(JSON.stringify(result));
} else {
  ['util', 'svg', 'theme', 'app', 'views'].forEach(function (key) {
    result.modules[key] = !!PM[key];
  });
  result.viewNames = PM.views ? Object.keys(PM.views).sort() : [];

  const data = JSON.parse(PAYLOAD_TEXT);

  /* PM.app registers itself on DOMContentLoaded or immediately; readyState is
     'complete' above, so init() has already run and the filter is live. */
  TAB_IDS.forEach(function (tab) {
    const panel = byId['tab-' + tab];
    const view = PM.views && PM.views[tab];
    if (typeof view !== 'function') {
      result.views[tab] = { present: false };
      return;
    }
    const before = created.total;
    panel.childNodes = [];
    try {
      view(panel, data);
      const nodes = flatten(panel).length;
      const svgs = flatten(panel).filter(n => n.namespaceURI === SVG_NS && n.tagName === 'svg').length;
      const emptyCards = flatten(panel).filter(n => n.classList && n.classList.contains('pm-empty')).length;
      const cards = flatten(panel).filter(n => n.classList && n.classList.contains('pm-card')).length;
      const tables = flatten(panel).filter(n => n.tagName === 'table').length;
      const kpis = flatten(panel).filter(n => n.classList && n.classList.contains('pm-kpi')).length;
      const text = panel.textContent || '';
      result.views[tab] = {
        present: true, ok: true, nodes: nodes, svgs: svgs, cards: cards,
        tables: tables, kpis: kpis, emptyStates: emptyCards,
        chars: text.length, allocated: created.total - before,
        suspectText: /\bNaN\b|\bundefined\b|\[object Object\]/.test(text),
      };
    } catch (err) {
      result.views[tab] = {
        present: true, ok: false,
        message: String(err && err.message || err),
        stack: String(err && err.stack || '').split('\n').slice(0, 6).join(' | '),
      };
    }
  });

  /* Idempotence: a second render must not accumulate. */
  TAB_IDS.forEach(function (tab) {
    const view = PM.views && PM.views[tab];
    if (typeof view !== 'function' || !result.views[tab].ok) return;
    const panel = byId['tab-' + tab];
    panel.childNodes = [];
    try {
      view(panel, data);
      const second = flatten(panel).length;
      if (second !== result.views[tab].nodes) {
        result.views[tab].idempotent = false;
        result.views[tab].secondNodes = second;
      } else {
        result.views[tab].idempotent = true;
      }
    } catch (err) {
      result.views[tab].idempotent = false;
      result.views[tab].secondError = String(err && err.message || err);
    }
  });

  /* An empty payload must degrade, not crash - that is the other project's
     first run, and the most likely place this front end breaks. */
  const bare = {
    schema_version: 2, generated_at: '', generator: { name: 'x', version: '0' },
    project: { name: 'empty', workflow_dir: '.ai', corpus_shape: 'sprint_brief', today: '2026-01-01', git_available: false },
    units: { primary: 'tasks', points_available: false, points_coverage: 0, points_total: null, size_proxy_note: '' },
    tasks: [], sprints: [], adhoc: [], backlog: [], phases: [], decisions: [], reviews: [], log: [], commits: [],
    defects: [], advisories: [],
    provenance: { date_sources: {}, git_baseline: { available: false }, floored_dates: 0, approximate_tasks: [], excluded_from_timeseries: [], estimates_present: false, sources_read: [], notes: [] },
    metrics: {
      as_of: '2026-01-01', window: { start: '2026-01-01', end: '2026-01-01', days: 0, weeks: 0 },
      series_granularity: 'day',
      totals: { tasks: 0, done: 0, pending: 0, unparseable: 0, in_progress: 0, blocked: 0, not_started: 0, sprints: 0, sprints_active: 0, sprints_closed: 0, sprints_planned: 0, decisions: 0, reviews: 0, adhoc_open: 0, adhoc_resolved: 0, log_entries: 0, commits: 0, insertions: 0, deletions: 0, tasks_with_dates: 0, tasks_without_dates: 0, completion_pct: 0 },
      kpis: [], burnup: [], burndown: [], cfd: [], velocity: [], velocity_avg: 0, velocity_stddev: 0,
      throughput: [],
      cycle_time: { samples: [], n: 0, avg: null, p50: null, p85: null, p95: null, max: null, usable: false },
      lead_time: { samples: [], n: 0, avg: null, p50: null, p85: null, p95: null, max: null, usable: false },
      aging_wip: [], scope_churn: [],
      forecast: { method: 'monte_carlo_weekly_throughput', usable: false, trials: 0, remaining: 0, sample_weeks: 0, sample_values: [], zero_weeks: 0, weeks: {}, percentiles: {}, histogram: [], cone: [], note: 'empty' },
      dependencies: { nodes: [], edges: [], layer_count: 0, cycles: [], critical_path: [], ready: [], prose_gated: [] },
      lanes: [], states: [],
      activity: { calendar: [], by_month: [], log_types: [], code_volume: [], top_areas: [] },
      debt: { adhoc_trend: [], open_items: [], adr_cadence: [], risks: [] },
    },
  };
  result.empty = {};
  TAB_IDS.forEach(function (tab) {
    const view = PM.views && PM.views[tab];
    if (typeof view !== 'function') return;
    const panel = byId['tab-' + tab];
    panel.childNodes = [];
    try {
      view(panel, bare);
      result.empty[tab] = { ok: true, nodes: flatten(panel).length };
    } catch (err) {
      result.empty[tab] = { ok: false, message: String(err && err.message || err),
                            stack: String(err && err.stack || '').split('\n').slice(0, 5).join(' | ') };
    }
  });

  console.log(JSON.stringify(result));
}
"""


def _token_values(asset_dir):
    """Real token values from the light block of 00-tokens.css."""
    path = Path(asset_dir) / "css" / "00-tokens.css"
    values = {}
    if not path.is_file():
        return values
    text = path.read_text(encoding="utf-8")
    # Both the :root shape/type block and the light palette, which together are
    # what a browser would resolve for the default theme.
    for match in re.finditer(r"(--pm-[a-z0-9-]+)\s*:\s*([^;]+);", text):
        values.setdefault(match.group(1), match.group(2).strip())
    return values


def _sources(asset_dir):
    out = []
    js_dir = Path(asset_dir) / "js"
    for path in sorted(js_dir.glob("*.js")):
        out.append({"name": path.name, "code": path.read_text(encoding="utf-8")})
    return out


def syntax_check(asset_dir=ASSET_DIR, node=None):
    """`node --check` every source. Cheap, and catches a parse error precisely."""
    node = node or shutil.which("node")
    if not node:
        return {"available": False, "results": []}
    results = []
    for path in sorted((Path(asset_dir) / "js").glob("*.js")):
        proc = subprocess.run(
            [node, "--check", str(path)], capture_output=True, text=True,
            encoding="utf-8", errors="replace", timeout=60,
        )
        results.append({
            "file": path.name,
            "ok": proc.returncode == 0,
            "error": (proc.stderr or "").strip()[:500] if proc.returncode else "",
        })
    return {"available": True, "results": results}


def run(payload=None, asset_dir=ASSET_DIR, node=None, timeout=180, root=None):
    """Load every source against `payload` and invoke every view."""
    node = node or shutil.which("node")
    if not node:
        return {
            "available": False,
            "ok": True,
            "reason": "node is not on PATH; the headless render check was skipped, "
                      "which is not evidence the dashboard works.",
        }

    if payload is None:
        import pm_dashboard

        payload = pm_dashboard.build_payload(root)

    driver = (
        "const TAB_IDS = %s;\n" % json.dumps(list(TABS))
        + "const PAYLOAD_TEXT = %s;\n" % json.dumps(
            json.dumps(payload, sort_keys=True, allow_nan=False)
        )
        + "const TOKEN_VALUES = %s;\n" % json.dumps(_token_values(asset_dir))
        + "const SOURCES = %s;\n" % json.dumps(_sources(asset_dir))
        + DOM_SHIM
    )

    with tempfile.TemporaryDirectory() as tmp:
        script = Path(tmp) / "smoke.mjs"
        script.write_text(driver, encoding="utf-8")
        proc = subprocess.run(
            [node, str(script)], capture_output=True, text=True,
            encoding="utf-8", errors="replace", timeout=timeout,
        )

    if proc.returncode != 0:
        return {
            "available": True, "ok": False,
            "reason": "the headless driver itself failed to run",
            "stderr": (proc.stderr or "").strip()[:4000],
        }

    line = ""
    for candidate in (proc.stdout or "").splitlines():
        if candidate.strip().startswith("{"):
            line = candidate.strip()
    if not line:
        return {
            "available": True, "ok": False,
            "reason": "the driver produced no JSON result",
            "stdout": (proc.stdout or "")[:2000],
            "stderr": (proc.stderr or "")[:2000],
        }

    report = json.loads(line)
    report["available"] = True
    report["ok"] = _verdict(report)
    report["stderr"] = (proc.stderr or "").strip()[:2000]
    return report


def _verdict(report):
    if report.get("fatal"):
        return False
    for key in ("util", "svg", "theme", "app", "views"):
        if not (report.get("modules") or {}).get(key):
            return False
    for tab, info in (report.get("views") or {}).items():
        if not info.get("present") or not info.get("ok"):
            return False
        if info.get("idempotent") is False:
            return False
        if info.get("suspectText"):
            return False
    for tab, info in (report.get("empty") or {}).items():
        if not info.get("ok"):
            return False
    for issue in report.get("issues") or []:
        if issue.get("kind") in ("load-error", "poison-attribute"):
            return False
    return True


def summarise(report):
    lines = []
    if not report.get("available"):
        lines.append("SKIPPED: " + report.get("reason", "node unavailable"))
        return lines

    if report.get("fatal"):
        lines.append("FATAL: " + report["fatal"])
        return lines
    if report.get("reason"):
        lines.append("FAIL: " + report["reason"])
        for key in ("stderr", "stdout"):
            if report.get(key):
                lines.append("  " + report[key][:1500].replace("\n", "\n  "))
        return lines

    modules = report.get("modules") or {}
    lines.append("modules: " + ", ".join(
        "%s=%s" % (k, "ok" if modules.get(k) else "MISSING")
        for k in ("util", "svg", "theme", "app", "views")
    ))
    lines.append("view functions registered: %d (%s)" % (
        len(report.get("viewNames") or []), ", ".join(report.get("viewNames") or [])
    ))
    lines.append("")
    lines.append("%-10s %-6s %6s %5s %5s %5s %5s %6s %s" % (
        "TAB", "STATE", "NODES", "SVG", "CARD", "TBL", "KPI", "EMPTY", "NOTE"
    ))
    for tab in TABS:
        info = (report.get("views") or {}).get(tab) or {}
        if not info.get("present"):
            lines.append("%-10s %-6s %s" % (tab, "ABSENT", "no view function"))
            continue
        if not info.get("ok"):
            lines.append("%-10s %-6s %s" % (tab, "THREW", info.get("message", "")))
            if info.get("stack"):
                lines.append("           %s" % info["stack"])
            continue
        notes = []
        if info.get("idempotent") is False:
            notes.append("NOT IDEMPOTENT (%s -> %s nodes)"
                         % (info.get("nodes"), info.get("secondNodes")))
        if info.get("suspectText"):
            notes.append("NaN/undefined IN VISIBLE TEXT")
        empty = (report.get("empty") or {}).get(tab) or {}
        if not empty.get("ok"):
            notes.append("crashes on empty payload: %s" % empty.get("message", ""))
        lines.append("%-10s %-6s %6d %5d %5d %5d %5d %6d %s" % (
            tab, "ok", info.get("nodes", 0), info.get("svgs", 0),
            info.get("cards", 0), info.get("tables", 0), info.get("kpis", 0),
            info.get("emptyStates", 0), "; ".join(notes),
        ))

    issues = report.get("issues") or []
    lines.append("")
    if issues:
        lines.append("ISSUES (%d):" % len(issues))
        seen = {}
        for issue in issues:
            key = (issue.get("kind"), issue.get("file") or issue.get("tag"),
                   issue.get("attr"))
            seen.setdefault(key, []).append(issue)
        for key, group in sorted(seen.items(), key=lambda kv: -len(kv[1])):
            first = group[0]
            if first.get("kind") == "load-error":
                lines.append("  [load-error] %s: %s" % (first.get("file"), first.get("message")))
                if first.get("stack"):
                    lines.append("               %s" % first["stack"])
            else:
                lines.append("  [%s] x%d  <%s %s=\"%s\">" % (
                    first.get("kind"), len(group), first.get("tag"),
                    first.get("attr"), first.get("value"),
                ))
    else:
        lines.append("ISSUES: none.")

    created = report.get("created") or {}
    lines.append("")
    lines.append("nodes created in total: %d (%d svg)"
                 % (created.get("total", 0), created.get("svg", 0)))
    lines.append("VERDICT: %s" % ("PASS" if report.get("ok") else "FAIL"))
    return lines


def main(argv=None):
    ap = argparse.ArgumentParser(
        description=(
            "Run the generated dashboard headlessly against a minimal DOM and "
            "report what rendered. Diagnostic: exits 0 even on failure unless "
            "--gate is given."
        )
    )
    ap.add_argument("--json", action="store_true", help="emit the raw report")
    ap.add_argument("--syntax-only", action="store_true",
                    help="only run `node --check` over each source")
    ap.add_argument("--gate", action="store_true",
                    help="exit 1 when the render check fails (a missing node "
                         "still exits 0, and says so)")
    ap.add_argument("--asset-dir", default=str(ASSET_DIR))
    ap.add_argument(
        "--root", default=None,
        help="render against another project's corpus instead of this one. The "
             "generator serves two corpus layouts, and a render check that only "
             "ever sees one of them cannot catch a view that breaks on the "
             "other — which is the whole reason this flag exists.",
    )
    args = ap.parse_args(argv)

    if args.syntax_only:
        result = syntax_check(args.asset_dir)
        if args.json:
            print(json.dumps(result, indent=2))
        elif not result["available"]:
            print("SKIPPED: node is not on PATH.")
        else:
            for entry in result["results"]:
                print("%-20s %s" % (entry["file"], "ok" if entry["ok"] else "PARSE ERROR"))
                if not entry["ok"]:
                    print("  " + entry["error"].replace("\n", "\n  "))
        bad = any(not e["ok"] for e in result["results"])
        return 1 if (args.gate and bad) else 0

    report = run(asset_dir=args.asset_dir, root=args.root)
    if args.json:
        print(json.dumps(report, indent=2, sort_keys=True))
    else:
        print("\n".join(summarise(report)))

    if args.gate and report.get("available") and not report.get("ok"):
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
