#!/usr/bin/env python3
"""Render a project's dashboard-publishing pipelines, and guard what they publish.

Driven by publish-dashboard.sh; see that file for usage. Standard library only.

WHY THIS EXISTS (TASK-0127, closing B-048). Publishing the dashboard to GitHub
Pages or GitLab Pages is optional - the destination's CI builds the page - and
it used to be a property of one repository: a hand-written workflow that
had learned, the hard way, that a shallow clone publishes a plausible page
that is wrong. A consumer of this skill got the generator and none of that.

The pipelines now ship here as templates, and a project's copy is RENDERED
from them, with `render --check` failing when the copy drifts. That is the only
route B-048 costed that cannot rot: an ungated copy is what B-040 found had
already rotted five times.

THE DAILY TARGET (TASK-0129). `github-pages-daily` is not a destination. It
renders a second GitHub workflow whose only job is to dispatch the
github-pages one once a day and wait for it, because the page is dated by the
day it is built. It is a file of its own for the reason ai-toolbox's ADR-0029
records; GitHub's limits on schedules are in references/dashboard.md. So it
`needs` github-pages, and the file it dispatches is read from TARGETS rather
than written into its template.

WHAT `render --check` PROVES: that each configured target's CI file is
exactly what its template renders to, and that GitLab's fragment is included.
WHAT IT DOES NOT PROVE: that the pipeline runs. A byte-exact copy of a
template nobody has run is still unrun; that is what the STATUS line in each
rendered file is for, and it moves only against an observed run.

WHAT `guard` PROVES: that the model a pipeline is about to publish came from a
full clone, with history, tasks and the expected corpus shape.
WHAT IT DOES NOT PROVE: that any figure on the page is true. The dashboard is a
view, not an audit (references/dashboard.md).
"""
import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SKILL = os.path.dirname(HERE)

CONF = "dashboard-publish.conf"
MARKER = "# GENERATED by "
GITLAB_CI = ".gitlab-ci.yml"
GITLAB_FRAGMENT = ".gitlab/ci/dashboard-pages.yml"


def asset(name):
    return os.path.join(SKILL, "assets", name)


# Each template is named by a literal string in an asset call, so
# tests/validate.sh can prove it exists and is tracked: its UNTRACKED ASSET
# check reads only literal calls, and a computed name would be invisible to it.
TARGETS = {
    "github-pages": {
        "template": asset("publish/github-pages.yml"),
        "out": ".github/workflows/dashboard.yml",
    },
    # Not a destination: a second GitHub workflow whose only job is to
    # dispatch the github-pages one once a day and wait for it. `needs` names
    # that target; load_conf refuses this one without it.
    "github-pages-daily": {
        "template": asset("publish/github-pages-daily.yml"),
        "out": ".github/workflows/dashboard-daily.yml",
        "needs": "github-pages",
    },
    "gitlab-pages": {
        "template": asset("publish/gitlab-pages.yml"),
        "out": GITLAB_FRAGMENT,
    },
}

REQUIRED = ("targets", "skill_dir", "branch")
OPTIONAL = ("root", "expect_shape")
SHAPES = ("numbered_task", "sprint_brief")
# A value interpolated into YAML and a shell command line. Deliberately narrow:
# anything wider is an injection surface for no benefit.
TOKEN = re.compile(r"^[A-Za-z0-9._/\-]+$")
PLACEHOLDER = re.compile(r"@@[A-Z_]+@@")
INCLUDE = re.compile(r"local:\s*['\"]?/?" + re.escape(GITLAB_FRAGMENT) + r"['\"]?\s*$",
                     re.MULTILINE)


class Refusal(Exception):
    """A condition the user must fix; exit 2 with the message."""


def say(msg):
    print("publish-dashboard.sh: %s" % msg, file=sys.stderr)


def read_text(path):
    with open(path, encoding="utf-8", newline="") as fh:
        # A Windows checkout with core.autocrlf rewrites line endings in the
        # working tree. That is not drift, and reporting it as drift would get
        # the check disabled.
        return fh.read().replace("\r\n", "\n")


def write_text(path, text):
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)


def load_conf(repo):
    path = os.path.join(repo, CONF)
    if not os.path.isfile(path):
        raise Refusal("no %s at the repository root. Publishing is optional; "
                      "the local file from build-dashboard.sh needs no config. "
                      "See references/dashboard.md, 'Publishing it'." % CONF)
    conf = {}
    for n, raw in enumerate(read_text(path).split("\n"), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            raise Refusal("%s:%d: expected `key = value`, got %r" % (CONF, n, raw))
        key, value = (part.strip() for part in line.split("=", 1))
        known = key in REQUIRED or key in OPTIONAL or (
            key.startswith("status.") and key[len("status."):] in TARGETS)
        if not known:
            raise Refusal("%s:%d: unknown key %r. Known: %s, status.<target>"
                          % (CONF, n, key, ", ".join(REQUIRED + OPTIONAL)))
        if key in conf:
            raise Refusal("%s:%d: %r is set twice" % (CONF, n, key))
        conf[key] = value

    missing = [k for k in REQUIRED if not conf.get(k)]
    if missing:
        raise Refusal("%s is missing %s" % (CONF, ", ".join(missing)))
    conf.setdefault("root", ".ai")

    targets = conf["targets"].split()
    unknown = [t for t in targets if t not in TARGETS]
    if unknown:
        raise Refusal("%s: unknown target(s) %s. Known: %s"
                      % (CONF, " ".join(unknown), " ".join(sorted(TARGETS))))
    if not targets:
        raise Refusal("%s: `targets` is empty" % CONF)
    conf["targets"] = targets
    for t in targets:
        need = TARGETS[t].get("needs")
        if need and need not in targets:
            raise Refusal("%s: %s dispatches the %s workflow (%s), so it needs "
                          "%s in targets too"
                          % (CONF, t, need, TARGETS[need]["out"], need))

    for key in ("skill_dir", "root", "branch", "expect_shape"):
        value = conf.get(key)
        if value and not TOKEN.match(value):
            raise Refusal("%s: %s=%r may hold only letters, digits and . _ / -"
                          % (CONF, key, value))
    shape = conf.get("expect_shape")
    if shape and shape not in SHAPES:
        raise Refusal("%s: expect_shape=%r; the generator detects %s"
                      % (CONF, shape, " or ".join(SHAPES)))

    for t in targets:
        status = conf.get("status." + t, "")
        # Forced, not defaulted: a pipeline with no status line reads as one
        # somebody vouched for.
        if not status:
            raise Refusal("%s: status.%s is required - say whether a run has "
                          "been observed, e.g. `UNVERIFIED - never run`" % (CONF, t))
        if "@@" in status:
            raise Refusal("%s: status.%s may not contain '@@'" % (CONF, t))
    return conf


def check_skill_dir(repo, conf):
    """The runner can only execute what is in its clone."""
    rel = conf["skill_dir"]
    if os.path.isabs(rel) or rel.split("/")[0] == ".." or "/../" in "/%s/" % rel:
        raise Refusal("skill_dir=%r must be a path inside the repository" % rel)
    full = os.path.join(repo, rel)
    real_repo = os.path.realpath(repo)
    real_skill = os.path.realpath(full)
    if os.path.commonpath([real_repo, real_skill]) != real_repo:
        raise Refusal(
            "skill_dir=%r resolves outside the repository (%s). A CI runner "
            "clones the repository and nothing else, so a skill installed in "
            "~/.claude/skills or linked in from elsewhere does not exist "
            "there. Copy skills/project-workflow into the repository and point "
            "skill_dir at the copy." % (rel, real_skill))
    need = ("scripts/build-dashboard.sh", "scripts/publish-dashboard.sh")
    for sub in need:
        if not os.path.isfile(os.path.join(full, sub)):
            raise Refusal("skill_dir=%r has no %s" % (rel, sub))
    tracked = git(repo, "ls-files", "--", *("%s/%s" % (rel, s) for s in need))
    if tracked is not None:
        have = set(tracked.split("\n"))
        untracked = [s for s in need if "%s/%s" % (rel, s) not in have]
        if untracked:
            raise Refusal("skill_dir=%r: %s not tracked by git, so a clone "
                          "will not have it" % (rel, ", ".join(untracked)))


# Variables that make git ignore `-C` and answer about some other repository.
# A pre-commit hook exports GIT_DIR and GIT_INDEX_FILE, so without this every
# question asked of `repo` from inside a hook is answered by the repository
# being committed to (TASK-0127, where that is exactly what happened).
GIT_LOCATORS = ("GIT_DIR", "GIT_WORK_TREE", "GIT_INDEX_FILE", "GIT_COMMON_DIR",
                "GIT_PREFIX", "GIT_OBJECT_DIRECTORY",
                "GIT_ALTERNATE_OBJECT_DIRECTORIES", "GIT_NAMESPACE")


def git(repo, *args):
    env = {k: v for k, v in os.environ.items() if k not in GIT_LOCATORS}
    try:
        out = subprocess.run(["git", "-C", repo] + list(args), env=env,
                             stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
    except OSError:
        return None
    if out.returncode != 0:
        return None
    return out.stdout.decode("utf-8", "replace").strip()


def render_one(target, conf):
    shape = conf.get("expect_shape")
    values = {
        "SKILL_DIR": conf["skill_dir"],
        "ROOT": conf["root"],
        "BRANCH": conf["branch"],
        "STATUS": conf["status." + target],
        "GUARD_ARGS": " --expect-shape %s" % shape if shape else "",
        "FRAGMENT": GITLAB_FRAGMENT,
        # The daily dispatcher names the pipeline it starts by file name, read
        # here so the pipeline's path keeps one owner.
        "PAGES_WORKFLOW": os.path.basename(TARGETS["github-pages"]["out"]),
    }
    text = read_text(TARGETS[target]["template"])
    for key, value in values.items():
        text = text.replace("@@%s@@" % key, value)
    left = PLACEHOLDER.findall(text)
    if left:
        raise Refusal("template %s has unfilled %s"
                      % (TARGETS[target]["template"], ", ".join(sorted(set(left)))))
    return text


def gitlab_stub(conf):
    return ("%s%s/scripts/publish-dashboard.sh, because this project had no\n"
            "# %s. It is yours to replace with your own CI: keep the include\n"
            "# below and `render --check` stays green.\n"
            "include:\n"
            "  - local: %s\n" % (MARKER, conf["skill_dir"], GITLAB_CI, GITLAB_FRAGMENT))


def render(repo, check, adopt):
    conf = load_conf(repo)
    check_skill_dir(repo, conf)
    stale = []

    for target in sorted(TARGETS):
        rel = TARGETS[target]["out"]
        path = os.path.join(repo, rel)
        exists = os.path.isfile(path)
        current = read_text(path) if exists else None

        if target not in conf["targets"]:
            # A generated file for a destination nobody configures any more
            # keeps deploying. Say so rather than leave it.
            if exists and current.startswith(MARKER):
                stale.append("%s was generated for %s, which is no longer in "
                             "targets - delete it" % (rel, target))
            continue

        want = render_one(target, conf)
        if current == want:
            print("ok       %s (%s)" % (rel, target))
            continue
        if exists and not current.startswith(MARKER) and not adopt:
            raise Refusal("%s exists and was not generated by this script; "
                          "refusing to overwrite it. Move it aside, or pass "
                          "--adopt to replace it with the rendered pipeline"
                          % rel)
        if check:
            stale.append("%s is %s; run `publish-dashboard.sh render`"
                         % (rel, "stale" if exists else "missing"))
            continue
        write_text(path, want)
        print("wrote    %s (%s)" % (rel, target))

    if "gitlab-pages" in conf["targets"]:
        ci = os.path.join(repo, GITLAB_CI)
        if not os.path.isfile(ci):
            if check:
                stale.append("%s is missing; run `publish-dashboard.sh render`"
                             % GITLAB_CI)
            else:
                write_text(ci, gitlab_stub(conf))
                print("wrote    %s (stub including %s)" % (GITLAB_CI, GITLAB_FRAGMENT))
        elif not INCLUDE.search(read_text(ci)):
            # Never edited: a project's CI file is its own. Only reported.
            stale.append("%s does not include the dashboard job. Add:\n"
                         "           include:\n"
                         "             - local: %s" % (GITLAB_CI, GITLAB_FRAGMENT))
        else:
            print("ok       %s (includes %s)" % (GITLAB_CI, GITLAB_FRAGMENT))

    for msg in stale:
        print("STALE    %s" % msg)
    return 1 if stale else 0


def guard(model_path, expect_shape, repo):
    bad = []
    try:
        with open(model_path, encoding="utf-8") as fh:
            model = json.load(fh)
    except (OSError, ValueError) as exc:
        bad.append("cannot read the model at %s: %s" % (model_path, exc))
        model = None

    if model is not None:
        # A missing key must FAIL. TASK-0125 found a guard reading keys the
        # payload no longer had: it read `undefined`, never fired, and the
        # deploy it was meant to stop looked checked.
        def field(*keys):
            node = model
            for k in keys:
                if not isinstance(node, dict) or k not in node:
                    bad.append("model has no %s - the generator's payload "
                               "changed shape; update this guard against "
                               "dashboard/SCHEMA.md" % ".".join(keys))
                    return None
                node = node[k]
            return node

        commits = field("metrics", "totals", "commits")
        tasks = field("metrics", "totals", "tasks")
        git_ok = field("project", "git_available")
        shape = field("project", "corpus_shape")
        if isinstance(commits, int) and commits <= 1:
            bad.append("git history is degenerate (%d commit(s)): every "
                       "completion date fell back to a hand-recorded field "
                       "and the Activity tab is empty" % commits)
        if isinstance(tasks, int) and tasks < 1:
            bad.append("no task brief parsed - the page would be empty")
        if git_ok is False:
            bad.append("git was unavailable to the generator")
        if expect_shape and shape is not None and shape != expect_shape:
            bad.append("corpus shape detected as %r, expected %r - every "
                       "count would come from a reader parsing the wrong "
                       "filenames" % (shape, expect_shape))

    # Asked of git, not inferred from a count: GitLab's default depth is 20,
    # and a 20-commit history passes every count-based check.
    shallow = git(repo, "rev-parse", "--is-shallow-repository")
    if shallow is None:
        bad.append("cannot ask git whether %s is a shallow clone" % repo)
    elif shallow == "true":
        bad.append("the clone is shallow, so the history the page reports is "
                   "truncated. Clone with full depth (GitHub: fetch-depth: 0; "
                   "GitLab: GIT_DEPTH: \"0\")")

    for msg in bad:
        # The ::error:: prefix is a GitHub annotation; GitLab prints it as-is.
        print("::error::%s" % msg)
    if bad:
        return 1
    print("history OK: %d commits, %d task briefs, shape %s, full clone"
          % (commits, tasks, shape))
    return 0


def main(argv):
    if not argv or argv[0] not in ("render", "guard"):
        say("expected a subcommand: render | guard (see --help)")
        return 2
    cmd, rest = argv[0], argv[1:]
    repo = None
    check = adopt = False
    model = shape = None
    i = 0
    while i < len(rest):
        arg = rest[i]
        if arg in ("--repo", "--model", "--expect-shape"):
            if i + 1 >= len(rest):
                say("%s needs a value" % arg)
                return 2
            value = rest[i + 1]
            if arg == "--repo":
                repo = value
            elif arg == "--model":
                model = value
            else:
                shape = value
            i += 2
            continue
        if arg == "--check" and cmd == "render":
            check = True
        elif arg == "--adopt" and cmd == "render":
            adopt = True
        else:
            say("%s: unknown argument %s" % (cmd, arg))
            return 2
        i += 1
    # Resolved only when --repo is absent: a git call on a /mnt/c checkout
    # costs ~70 ms over the 9p bridge, which the suite paid on every case.
    if repo is None:
        repo = git(os.getcwd(), "rev-parse", "--show-toplevel") or os.getcwd()
    repo = os.path.abspath(repo)
    try:
        if cmd == "render":
            if check and adopt:
                raise Refusal("--check and --adopt together make no sense")
            return render(repo, check, adopt)
        if not model:
            raise Refusal("guard needs --model PATH")
        return guard(model, shape, repo)
    except Refusal as exc:
        say(str(exc))
        return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
