#!/usr/bin/env bash
# Generate docs/registry.md — the index of every deployable component.
#
# One emit path serves every section. The three component kinds differ in
# only three ways: where their components live, how their name/description
# are extracted (YAML frontmatter, TOML, or JSON), and whether a Shape
# column applies. Everything common — the header, the template skip,
# sorted output, the `?` fallback — lives here once.
#
# That single template skip is the point: the rule "templates are not
# deployable components" previously existed once per section, so adding it
# to one section did not reach the others, and the same leak had to be
# fixed three times (TASK-0005, TASK-0006, TASK-0008). See B-007 /
# TASK-0011. tests/validate.sh independently asserts that no generated row
# points at a _template* path, so a regression here fails a check rather
# than reaching a commit.
set -euo pipefail
cd "$(dirname "$0")/.."
REG=docs/registry.md

# Strip one matching pair of surrounding quotes from a YAML scalar.
#
# TASK-0018: without this, a quoted `description: "..."` reached the
# registry with its quotes intact, while an unquoted one did not — so the
# defect was visible only in the two components that quote their
# frontmatter and invisible in the rest. ADR-0008's skill linter accepts
# both forms deliberately, which is correct: the *generator* normalizes,
# the schema does not dictate style.
#
# Only a matching leading/trailing pair is removed, so a description that
# merely contains a quote is untouched.
unquote() {
  local s="$1"
  case "$s" in
    '"'*'"') [ ${#s} -ge 2 ] && s="${s:1:${#s}-2}" ;;
    "'"*"'") [ ${#s} -ge 2 ] && s="${s:1:${#s}-2}" ;;
  esac
  printf '%s' "$s"
}

# Print "name<TAB>description" for one component directory, or nothing if
# the directory does not hold that kind of component.
#   $1 = kind (skill|mcp|loop), $2 = component directory
extract() {
  local kind="$1" d="$2" f
  case "$kind" in
    skill|loop)
      # Both kinds carry YAML frontmatter with the same two keys; they
      # differ only in filename.
      case "$kind" in
        skill) f="$d/SKILL.md" ;;
        loop)  f="$d/loop.md" ;;
      esac
      [ -f "$f" ] || return 1
      printf '%s\t%s\n' \
        "$(unquote "$(awk '/^name:/{sub(/^name: */,"");print;exit}' "$f")")" \
        "$(unquote "$(awk '/^description:/{sub(/^description: */,"");print;exit}' "$f")")"
      ;;
    mcp)
      # Two shapes (ADR-0005): authored Python packages carry
      # pyproject.toml, external upstream packages carry server.json.
      # Shape is derived from which marker file is present, never
      # self-declared, so it cannot contradict the directory's contents.
      if [ -f "$d/pyproject.toml" ]; then
        f="$d/pyproject.toml"
        printf '%s\t%s\t%s\n' \
          "$(grep '^name = ' "$f" | head -1 | sed 's/name = //;s/"//g')" \
          "$(grep '^description = ' "$f" | head -1 | sed 's/description = //;s/"//g')" \
          python
      elif [ -f "$d/server.json" ]; then
        python3 -c '
import json, sys
m = json.load(open(sys.argv[1]))
print("%s\t%s\texternal" % (m.get("name", "?"),
                            m.get("description", "").replace("\n", " ")))
' "$d/server.json"
      else
        return 1
      fi
      ;;
  esac
}

# Emit one registry section.
#   $1 = section title, $2 = kind, $3 = parent directory
#   $4 = "shape" to include the Shape column, empty otherwise
emit_section() {
  local title="$1" kind="$2" parent="$3" with_shape="${4:-}"
  echo "## $title"
  if [ -n "$with_shape" ]; then
    echo "| Name | Shape | Description | Path |"
    echo "|------|-------|-------------|------|"
  else
    echo "| Name | Description | Path |"
    echo "|------|-------------|------|"
  fi
  [ -d "$parent" ] || return 0
  local d base meta name desc shape
  # Sorted for a stable diff across filesystems.
  for d in $(printf '%s\n' "$parent"/*/ | sed 's:/$::' | sort); do
    base=$(basename "$d")
    # THE template skip. One place, all sections.
    case "$base" in _template*) continue ;; esac
    meta=$(extract "$kind" "$d") || continue
    IFS=$'\t' read -r name desc shape <<<"$meta"
    if [ -n "$with_shape" ]; then
      echo "| ${name:-?} | ${shape:-?} | ${desc:-} | $d |"
    else
      echo "| ${name:-?} | ${desc:-} | $d |"
    fi
  done
}

{
  echo "# Component Registry"
  echo
  echo "GENERATED by scripts/sync-registry.sh — do not hand-edit."
  echo
  emit_section "Skills"      skill skills
  echo
  emit_section "MCP Servers" mcp   mcp-servers shape
  echo
  emit_section "Loops"       loop  loops
} > "$REG"
echo "Registry written to $REG"
