#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
REG=docs/registry.md
{
  echo "# Component Registry"
  echo
  echo "GENERATED by scripts/sync-registry.sh — do not hand-edit."
  echo
  echo "## Skills"
  echo "| Name | Description | Path |"
  echo "|------|-------------|------|"
  for f in skills/*/SKILL.md; do
    [ -f "$f" ] || continue
    d=$(dirname "$f")
    # Templates are not deployable components; keep them out of the index
    # (same rule as the MCP loop below).
    case "$(basename "$d")" in _template*) continue ;; esac
    name=$(awk '/^name:/{sub(/^name: */,"");print;exit}' "$f")
    desc=$(awk '/^description:/{sub(/^description: */,"");print;exit}' "$f")
    echo "| ${name:-?} | ${desc:-} | $d |"
  done
  echo
  echo "## MCP Servers"
  echo "| Name | Shape | Description | Path |"
  echo "|------|-------|-------------|------|"
  # Two shapes (ADR-0005): authored Python packages carry pyproject.toml,
  # external upstream packages carry server.json. Shape is derived from
  # which file is present, never self-declared. Sorted for a stable diff.
  for d in $(printf '%s\n' mcp-servers/*/ | sed 's:/$::' | sort); do
    case "$(basename "$d")" in _template*) continue ;; esac
    if [ -f "$d/pyproject.toml" ]; then
      f="$d/pyproject.toml"
      name=$(grep '^name = ' "$f" | head -1 | sed 's/name = //;s/"//g')
      desc=$(grep '^description = ' "$f" | head -1 | sed 's/description = //;s/"//g')
      echo "| ${name:-?} | python | ${desc:-} | $d |"
    elif [ -f "$d/server.json" ]; then
      read -r name desc < <(python3 -c '
import json, sys
m = json.load(open(sys.argv[1]))
print(m.get("name", "?"), m.get("description", "").replace("\n", " "))
' "$d/server.json")
      echo "| ${name:-?} | external | ${desc:-} | $d |"
    fi
  done
  echo
  echo "## Loops"
  echo "| Name | Description | Path |"
  echo "|------|-------------|------|"
  for f in loops/*/loop.md; do
    [ -f "$f" ] || continue
    d=$(dirname "$f")
    case "$(basename "$d")" in _template*) continue ;; esac
    name=$(awk '/^name:/{sub(/^name: */,"");print;exit}' "$f")
    desc=$(awk '/^description:/{sub(/^description: */,"");print;exit}' "$f")
    echo "| ${name:-?} | ${desc:-} | $d |"
  done
} > "$REG"
echo "Registry written to $REG"
